# Site settings
title: Paramvir Rotwal
description: Paramvir Rotwal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Paramvir Rotwal
user_description: I am currently pursuing my Bachelor's degree in Information Technology from University of Mumbai. Focused on learning DevOps and exploring the Cloud Computing Services. • Implementing my skills using Java, Spring Boot, AWS, HTML, CSS, JavaScript. • Hands on using AWS services like EC2, IAM, S3, RDS, EBS, VPC, AWS Lambda, ECS, CodeBuild, etc. • Implementing DevOps Methodologies on cloud services. • Coded Web Applications using Microservices like Java, Spring Boot, Hibernate. Using Linux as my primary OS, proficient in Shell Scripting using Bash.

user_title: DevOps and Cloud
email: paramvirrotwal@gmail.com
# twitter_username: lorem_ipsum
instagram_username: pveer_55
linkedin_username: paramvir-rotwal
github_username:  pveerrotwal
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

